# Generated by Django 3.2.23 on 2023-11-27 18:35

from django.db import migrations


def convert_to_price_range(price):
    if price <= 10000:
        return 'L'
    elif price <= 100000: 
        return 'M'
    else:
        return 'H'

def save_item_price_range(apps, schema_editor):
    Post = apps.get_model('podomarket', 'Post')
    for post in Post.objects.all():
        post.item_price_range = convert_to_price_range(post.item_price)
        post.save()


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0007_post_item_price_range'),
    ]

    operations = [
        migrations.RunPython(save_item_price_range, migrations.RunPython.noop),
    ]
