# Generated by Django 3.2.23 on 2023-12-01 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0008_like'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['dt_created']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-dt_created']},
        ),
    ]
