"""
Django settings for coplate_project project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'pb5d%w0u@hu_=8f70_=vn6)ova&1mzqxe0em*$zstcm+*=geec'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'coplate',
    'widget_tweaks',
    # Auth Setting
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
]

SITE_ID = 1 # 각 SITE들을 구분해줌

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'coplate.middleware.ProfileSetUpMiddleWare',
]

ROOT_URLCONF = 'coplate_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'coplate_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
      "NAME" : "coplate.validators.CustomPasswordValidator",  
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'ko'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATIC_URL = "/static/"
MEDIA_ROOT = os.path.join(BASE_DIR,"media")
MEDIA_URL = "/uploads/"

# Auth Setting

AUTH_USER_MODEL = 'coplate.User' # User 모델을 auth_user_model로 사용할거라고 알려줌. 추후 migrate때 사용

AUTHENTICATION_BACKENDS = [
    
    # Needed to login by username in Django admin, regardless of `allauth`
    'django.contrib.auth.backends.ModelBackend',

    # `allauth` specific authentication methods, such as login by email
    'allauth.account.auth_backends.AuthenticationBackend',
    
]

ACCOUNT_SIGNUP_REDIRECT_URL = "profile-set" # 사용자가 회원가입 후 이동할 url
LOGIN_REDIRECT_URL = 'index' # 사용자가 로그인 후 이동할 url
LOGIN_URL = 'account_login' # 어느 url에서 로그인을 하니?
ACCOUNT_LOGOUT_ON_GET = True # 로그아웃 누르면 바로 로그아웃
ACCOUNT_AUTHENTICATION_METHOD = 'email' # 회원가입 시 아이디 뭐로 할거? email
ACCOUNT_EMAIL_REQUIRED = True # 이메일 입력 칸 만듬
ACCOUNT_USERNAME_REQUIRED = False # username 입력 칸 없애기
# ACCOUNT_SIGNUP_FORM_CLASS = "coplate.forms.SignupForm" # modelform 선언해주기
ACCOUNT_SESSION_REMEMBER = True # user 기억하기
ACCOUNT_PASSWORD_INPUT_RENDER_VALUE = True # 회원가입 실패해도 비밀번호가 사라지지 않음
ACCOUNT_EMAIL_VERIFICATION = "optional" # email 입력이 선택임
ACCOUNT_CONFIRM_EMAIL_ON_GET = True 
ACCOUNT_EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL = "account_email_confirmation_done"
ACCOUNT_EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL = "account_email_confirmation_done"
# SESSION_COOKIE_AGE = 3600 # 쿠키는 1시간 이후로 사라짐, 그리고 default값이 1시간임
PASSWORD_TIMEOUT_RESET_DAY = 3
ACCOUNT_EMAIL_SUBJECT_PREFIX = ""

# email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = "pokjm99@gmail.com"
EMAIL_HOST_PASSWORD = "zynh ysin xifn lxsh"