# Generated by Django 3.2.23 on 2023-11-22 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('podomarket', '0004_auto_20231122_0528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='item_condition',
            field=models.CharField(choices=[('새제품', '새제품'), ('최상', '최상'), ('상', '상'), ('중', '중'), ('하', '하')], default=None, max_length=10),
        ),
    ]
