# Generated by Django 2.2 on 2023-11-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img_path',
            field=models.ImageField(max_length=255, upload_to=''),
        ),
    ]
