# Generated by Django 2.2 on 2023-11-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20231105_0855'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='img_path',
            field=models.CharField(max_length=255),
        ),
    ]
