# Generated by Django 3.2.23 on 2023-11-21 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coplate', '0004_auto_20231121_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(null=True),
        ),
    ]
